version: "3"
services:
  pagila:
    image: postgres:13.2
    container_name: pagila
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pagila
    env_file:
      - .env
    volumes:
      - ./Data/pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./Data/pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pagila-star:
    image: postgres:13.2
    container_name: pagila-star
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pagila-star
    env_file:
      - .env
    volumes:
      - ./Data/pagila-star.sql:/docker-entrypoint-initdb.d/pagila-star.sql
      - ./pgstardata:/var/lib/postgresql/data
    ports:
      - 5433:5432